### ISSUE TITLE
Could not open input file: bin/phpspec

### ISSUE THREAD

**Issue by Lionel-Daelemans** [richardmiller/BehatSpec#7]
Hi, it's me again... (-_-)'

Well everything was running smooth until I hit the rerun step, then :

```
Could not open input file: bin/phpspec
```

As explained in the README, I've edited the `phpspec.yml` to override the default path but it doesn't seems to work. Any ideas?

You can test the bug on my [project repo](https://github.com/Lionel-Daelemans/advent_of_code_2015/tree/better-bdd) running `behat --suite=DayTest`.

**Comment by pocky** [comment]
Hello,

The documentation is wrong, your `phpspec.yml` should be: 

```yml
rerunner:
     path: vendor/bin/phpspec
     commands: [describe, exemplify]

extensions:
- RMiller\BehatSpec\PhpSpecExtension
```

Sorry, we will fix it.
